package tampilan;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

public class Hilangdanrusak extends javax.swing.JFrame {
    private Connection conn = koneksi.getKoneksi();
    private DefaultTableModel tabmode;
    
    public Hilangdanrusak() {
        initComponents();
        tampilkanData();
        kosongkanForm();
    }
    
    private void tampilkanData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Kasus");
    model.addColumn("Tanggal Lapor");
    model.addColumn("ID Petugas");
    model.addColumn("ID Anggota");
    model.addColumn("ID Buku");
    model.addColumn("Kondisi");
    model.addColumn("Jumlah");
    model.addColumn("Denda Ganti Rugi");
    model.addColumn("Status Solusi");

    try {
        String sql = "SELECT * FROM buku_rusak_hilang ORDER BY id_kasus ASC";
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_kasus"),
                rs.getString("tanggal_lapor"),
                rs.getString("id_petugas"),
                rs.getString("id_anggota"),
                rs.getString("id_buku"),
                rs.getString("jenis_kondisi"),
                rs.getString("jumlah"),
                rs.getString("denda_ganti_rugi"),
                rs.getString("status_solusi")
            });
        }
        tblhilang.setModel(model);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
    }
}

private void kosongkanForm() {
    txtkasus.setText("");
    txtkasus.setEditable(true); // Supaya bisa diinput untuk data baru
    txtlapor.setDate(new java.util.Date());
    txtpetugas.setText("");
    txtanggota.setText("");
    txtbuku.setText("");
    boxkondisi.setSelectedIndex(0);
    txtjumlah.setText("");
    txtdenda.setText("");
    boxstatus.setSelectedIndex(0);
    txtcari.setText("");
}

private void cariData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Kasus");
    model.addColumn("Tanggal Lapor");
    model.addColumn("ID Petugas");
    model.addColumn("ID Anggota");
    model.addColumn("ID Buku");
    model.addColumn("Kondisi");
    model.addColumn("Jumlah");
    model.addColumn("Denda Ganti Rugi");
    model.addColumn("Status Solusi");

    try {
        String sql = "SELECT * FROM buku_rusak_hilang WHERE id_kasus LIKE ? OR jenis_kondisi LIKE ? OR status_solusi LIKE ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        String keyword = "%" + txtcari.getText() + "%";
        ps.setString(1, keyword);
        ps.setString(2, keyword);
        ps.setString(3, keyword);
        
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_kasus"),
                rs.getString("tanggal_lapor"),
                rs.getString("id_petugas"),
                rs.getString("id_anggota"),
                rs.getString("id_buku"),
                rs.getString("jenis_kondisi"),
                rs.getString("jumlah"),
                rs.getString("denda_ganti_rugi"),
                rs.getString("status_solusi")
            });
        }
        tblhilang.setModel(model);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Pencarian gagal: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblhilang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtkasus = new javax.swing.JTextField();
        txtlapor = new de.wannawork.jcalendar.JCalendarComboBox();
        txtpetugas = new javax.swing.JTextField();
        txtanggota = new javax.swing.JTextField();
        txtbuku = new javax.swing.JTextField();
        boxkondisi = new javax.swing.JComboBox<>();
        txtjumlah = new javax.swing.JTextField();
        txtdenda = new javax.swing.JTextField();
        boxstatus = new javax.swing.JComboBox<>();
        bsimpan = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblhilang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblhilang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblhilangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblhilang);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Daftar Buku Hilang & Rusak");

        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });

        bcari.setText("Cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtcari))
                        .addGap(18, 18, 18)
                        .addComponent(bcari)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Form Buku Hilang & Rusak");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("ID Kasus");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Tanggal Lapor");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("ID Petugas");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("ID Anggota");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("ID Buku");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Kondisi");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Jumlah");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Denda Ganti Rugi");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Status Solusi");

        boxkondisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hilang", "Rusak", " " }));

        boxstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Selesai", "Sudah Diganti", "Denda Lunas" }));

        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bbatal.setText("Batal");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });

        bkeluar.setText("Keluar");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(267, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(258, 258, 258))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(bsimpan))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtkasus)
                                .addComponent(txtlapor, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                .addComponent(txtpetugas)
                                .addComponent(txtanggota)
                                .addComponent(txtbuku)
                                .addComponent(boxkondisi, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtjumlah)
                                .addComponent(txtdenda)
                                .addComponent(boxstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bbatal)
                                .addGap(100, 100, 100)
                                .addComponent(bkeluar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtkasus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtlapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtanggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(boxkondisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtdenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(boxstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsimpan)
                    .addComponent(bbatal)
                    .addComponent(bkeluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblhilangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhilangMouseClicked
    int baris = tblhilang.getSelectedRow();
    if (baris != -1) {
        txtkasus.setText(tblhilang.getValueAt(baris, 0).toString());
        // Untuk txtlapor (tanggal), Anda bisa menyesuaikannya jika diperlukan pembaruan objek Date
        txtpetugas.setText(tblhilang.getValueAt(baris, 2).toString());
        txtanggota.setText(tblhilang.getValueAt(baris, 3).toString());
        txtbuku.setText(tblhilang.getValueAt(baris, 4).toString());
        boxkondisi.setSelectedItem(tblhilang.getValueAt(baris, 5).toString());
        txtjumlah.setText(tblhilang.getValueAt(baris, 6).toString());
        txtdenda.setText(tblhilang.getValueAt(baris, 7).toString());
        boxstatus.setSelectedItem(tblhilang.getValueAt(baris, 8).toString());
    }
    }//GEN-LAST:event_tblhilangMouseClicked

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Kasus");
    model.addColumn("Tanggal Lapor");
    model.addColumn("ID Petugas");
    model.addColumn("ID Anggota");
    model.addColumn("ID Buku");
    model.addColumn("Kondisi");
    model.addColumn("Jumlah");
    model.addColumn("Denda");
    model.addColumn("Status Solusi");
    
    try {
        String sql = "SELECT * FROM buku_rusak_hilang WHERE id_anggota LIKE ? OR jenis_kondisi LIKE ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, "%" + txtcari.getText() + "%");
        ps.setString(2, "%" + txtcari.getText() + "%");
        ResultSet rs = ps.executeQuery();
        
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_kasus"),
                rs.getString("tanggal_lapor"),
                rs.getString("id_petugas"),
                rs.getString("id_anggota"),
                rs.getString("id_buku"),
                rs.getString("jenis_kondisi"),
                rs.getString("jumlah"),
                rs.getString("denda_ganti_rugi"),
                rs.getString("status_solusi")
            });
        }
        tblhilang.setModel(model);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Pencarian gagal: " + e.getMessage());
    }
    }//GEN-LAST:event_bcariActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
    String tanggal = sdf.format(txtlapor.getDate());
    
    // Validasi input kosong
    if (txtpetugas.getText().isEmpty() || txtanggota.getText().isEmpty() || txtbuku.getText().isEmpty() || txtjumlah.getText().isEmpty() || txtdenda.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Semua data harus diisi!");
        return;
    }

    try {
        String sql = "INSERT INTO buku_rusak_hilang (tanggal_lapor, id_buku, id_anggota, id_petugas, jenis_kondisi, jumlah, denda_ganti_rugi, status_solusi) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, tanggal);
        ps.setInt(2, Integer.parseInt(txtbuku.getText()));
        ps.setInt(3, Integer.parseInt(txtanggota.getText()));
        ps.setInt(4, Integer.parseInt(txtpetugas.getText()));
        ps.setString(5, boxkondisi.getSelectedItem().toString());
        ps.setInt(6, Integer.parseInt(txtjumlah.getText()));
        ps.setInt(7, Integer.parseInt(txtdenda.getText()));
        ps.setString(8, boxstatus.getSelectedItem().toString());
        
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan!");
        tampilkanData();
        kosongkanForm();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal menyimpan transaksi: " + e.getMessage());
    }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
    kosongkanForm();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
    int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (konfirmasi == JOptionPane.YES_OPTION) {
        dispose(); // Menutup form ini
    }
    }//GEN-LAST:event_bkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
    UIManager.setLookAndFeel(new FlatIntelliJLaf());
    } catch(Exception ex) {
        System.err.println("gagal memuat tema");
    }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hilangdanrusak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcari;
    private javax.swing.JButton bkeluar;
    private javax.swing.JComboBox<String> boxkondisi;
    private javax.swing.JComboBox<String> boxstatus;
    private javax.swing.JButton bsimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblhilang;
    private javax.swing.JTextField txtanggota;
    private javax.swing.JTextField txtbuku;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtdenda;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtkasus;
    private de.wannawork.jcalendar.JCalendarComboBox txtlapor;
    private javax.swing.JTextField txtpetugas;
    // End of variables declaration//GEN-END:variables
}
